# Generated by Django 4.1 on 2022-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country_of_origin", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["name"], name="brands_bran_name_9380ef_idx"),
        ),
    ]
