# Generated by Django 4.1 on 2022-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nib_size", models.CharField(max_length=1)),
                ("nib_material", models.CharField(max_length=100)),
                ("colour", models.CharField(max_length=100)),
                ("purchase_price", models.FloatField()),
                ("purchase_currency", models.CharField(max_length=3)),
                ("retailer", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name="pen",
            index=models.Index(
                fields=["nib_size", "colour", "purchase_currency"],
                name="pens_pen_nib_siz_de99a1_idx",
            ),
        ),
    ]
