# Generated by Django 4.1 on 2022-08-16 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0001_initial"),
        ("pens", "0002_alter_pen_nib_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="pen",
            name="brand",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="brands.brand",
            ),
            preserve_default=False,
        ),
    ]
