# Generated by Django 4.1 on 2022-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pens", "0003_pen_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="pen",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
