# Generated by Django 4.1 on 2022-08-16 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pens", "0004_pen_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pen",
            name="purchased_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
