# Generated by Django 4.1 on 2022-08-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pens", "0005_pen_purchased_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="pen",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
